image: node:latest

services:
  - mysql:latest
  - redis:latest
  - postgres:latest

stages:
  - test
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: ap-southeast-1
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

cache:
  paths:
    - app/nodejs/node_modules/
    - .npm/

before_script:
  - apk add --update npm # Ensure npm is installed
  - cd app/nodejs # Change directory to where package.json is located

unit_test:
  stage: test
  script:
    - npm install
    - npm run lint
    - npm run test
  only:
    - branches
  except:
    - master

build:
  stage: build
  script:
    - npm run build # Replace with your actual build command
  artifacts:
    paths:
      - build/ # Adjust according to your build output
  only:
    - master

deploy_to_aws:
  stage: deploy
  script:
    - terraform init
    - terraform apply -auto-approve
  only:
    - master
  environment:
    name: production
    url: http://your.production.domain # Replace with your actual production URL
