image: node:latest

services:
  - name: mysql:latest
    alias: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: mysql_strong_password
      MYSQL_DATABASE: my_db
  - redis:latest
  - name: postgres:latest
    alias: postgres
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres_strong_password

stages:
  - test
  - build
  - deploy

variables:
  MYSQL_DATABASE: my_db
  MYSQL_USER: user
  MYSQL_PASSWORD: mysql_strong_password
  MYSQL_ROOT_PASSWORD: mysql_strong_password
  POSTGRES_DB: my_db
  POSTGRES_USER: user
  POSTGRES_PASSWORD: postgres_strong_password
  REDIS_URL: "redis://redis"
  NODE_ENV: "test"

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update -y && apt-get install -y npm
  - npm install

unit_test:
  stage: test
  script:
    - npm run lint
    - npm run test
  only:
    - branches
  except:
    - master

build:
  stage: build
  script:
    - npm run build
  only:
    - master

deploy_to_aws:
  stage: deploy
  script:
    - npm install -g aws-cdk
    - cdk deploy --require-approval never
  only:
    - master
  environment:
    name: production