image: node:latest

stages:
  - test
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: ap-southeast-1
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

cache:
  paths:
    - node_modules/

before_script:
  - npm install

unit_test:
  stage: test
  script:
    - npm run lint
    - npm run test
  only:
    - branches
  except:
    - master

build:
  stage: build
  script:
    - npm run build
  only:
    - master

deploy_to_aws:
  stage: deploy
  script:
    - terraform init
    - terraform apply -auto-approve
  only:
    - master
  environment:
    name: production
    url: http://your.production.domain
